"""Initial catalog models

Revision ID: 53114a9f9105
Revises:
Create Date: 2026-09-29 09:52:54.438573

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "53114a9f9105"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
